output_folder: /data

variants:
  - name: Small Cloud Native ENM
    short_name: Small cENM
    offering: cENM
    id: eric-enm-integration-production-values
  - name: Extra-Large Cloud Native ENM
    short_name: Extra-Large cENM
    offering: cENM
    id: eric-enm-integration-extra-large-production-values
  - name: Internal test Multi Instance Cloud Native ENM
    short_name: Multi-Instance cENM
    offering: cENM
    id: eric-enm-multi-instance-functional-integration-values
  - name: Internal test Single Instance Cloud Native ENM
    short_name: Single-Instance cENM
    offering: cENM
    id: eric-enm-single-instance-production-integration-values
  - name: Standard Size Commercial Deployment EIC
    short_name: Standard-Size EIC
    offering: EIC
    id: eric-eic-integration-fixed-size-production-values
